export const CASE_LIBRARY = {
  EG: {
    'EG-1': [
      { name: 'PBL-0', alg: "y' R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
      { name: 'Sune-0', alg: "U2 R U R' U F R U' R2 F' R" },
      { name: 'Anti-Sune-0', alg: "U R' F R2 U R' F' U' R U' R'" },
      { name: 'Pi-0', alg: "U2 F2 R U R' U2 R U R' U' F" },
      { name: 'U-0', alg: "R U R' U F R' F' R2 U' R' F R' F' R" },
      { name: 'L-0', alg: "F R U' R' U' R U R' F'" },
      { name: 'T-0', alg: "R U R' U' R' F R F'" },
      { name: 'H-0', alg: "R2 U2 R' U2 R2" },
    ],
    'EG-2': [
      { name: 'PBL-0', alg: "F R2 U2 R' U R U2 R2 F R F' R' F'" },
      { name: 'Sune-0', alg: "U' F U' R2 U' R' U2 R U' R2 F'" },
      { name: 'Anti-Sune-0', alg: "U2 R' U R U' R2 F R F' R U R' U' R' F2 R2" },
      { name: 'Pi-0', alg: "F U' R U2 R U' R' U R' F'" },
      { name: 'U-0', alg: "F U' R U2 R U' R' U2 R' U' F'" },
      { name: 'L-0', alg: "R' U' R' F' R U' R U' R' F R" },
      { name: 'T-0', alg: "F R F' R U R' U' R B2 R2" },
      { name: 'H-0', alg: "U R2 F U2 F2 R2 F' R2" },
    ],
    'LEG-1': [
      { name: 'PBL-0', alg: "R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
      { name: 'Sune-0', alg: "U2 R' F U2 R2 F R'" },
      { name: 'Anti-Sune-0', alg: "U2 x' R U' R2 U R2 B2 R'" },
      { name: 'Pi-0', alg: "U' R F R' F' U R U' R2 F R F'" },
      { name: 'U-0', alg: "R U' R U R' U R U R2" },
      { name: 'L-0', alg: "U' R U2 F R' F' R U2 R U R2" },
      { name: 'T-0', alg: "U' R U2 R' U R U2 R' F R' F' R" },
      { name: 'H-0', alg: "R F2 R F' R' F U' F" },
    ],
    CLL: [
      { name: 'PBL-0', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
      { name: 'Sune-0', alg: "R U R' U R U2 R'" },
      { name: 'Anti-Sune-0', alg: "R' U' R U' R' U2 R" },
      { name: 'Pi-0', alg: "R U' R2 U R2 U R2 U' R" },
      { name: 'U-0', alg: "F R U R' U' F'" },
      { name: 'L-0', alg: "F R U' R' U' R U R' F'" },
      { name: 'T-0', alg: "R U R' U' R' F R F'" },
      { name: 'H-0', alg: "R2 U2 R' U2 R2" },
    ],
  },
  TCLL: {
    'TCLL+': [
      { name: 'Hammer-0', alg: "R' F R F' R' F R F'" },
      { name: 'Spaceship-0', alg: "U2 y' R' U' R U R' U' R" },
      { name: 'Stollery-0', alg: "R U R' U F' R U' R' F2" },
      { name: 'Pinwheel-0', alg: "y' F' R U R U2 R2 F' U R F'" },
      { name: 'Two-Face-0', alg: "U R U R' U' R2 U R2 U' R2" },
      { name: 'Turtle-0', alg: "R U' R' U R U' R'" },
      { name: 'Gun-0', alg: "R U' R' U2 R U2 R'" },
    ],
    'TCLL-': [
      { name: 'Hammer-0', alg: "U' F R' F' R F R' F' R" },
      { name: 'Spaceship-0', alg: "R U R' U' R U R'" },
      { name: 'Stollery-0', alg: "U2 F2 R U R' F U' R U' R'" },
      { name: 'Pinwheel-0', alg: "R2 U R' U R' U2 R U2 R' U2 R" },
      { name: 'Two-Face-0', alg: "R2 U R' U R U2 R' U2 R'" },
      { name: 'Turtle-0', alg: "U' y R' F R U' R' F R" },
      { name: 'Gun-0', alg: "U R U2 R' U2 R U R'" },
    ],
  },
  LS: {
    LS1: [{ name: 'LS1-0', alg: "F2 R2 U' R' F R' F2 R U' R'" }],
    LS2: [{ name: 'LS2-0', alg: "U F2 U R U R' U2 F2 R U' R'" }],
    LS3: [{ name: 'LS3-0', alg: "U2 y' R U' R2 U' R F R' F' R" }],
    LS4: [{ name: 'LS4-0', alg: "F R U2 R' U R U' R' F" }],
    LS5: [{ name: 'LS5-0', alg: "R' F R2 U2 R' U R U' R' F" }],
    LS6: [{ name: 'LS6-0', alg: "U2 y' R U' R2 U' R F R' F' R" }],
    LS7: [{ name: 'LS7-0', alg: "R' U R U' R2 U' F R F' R" }],
    LS8: [{ name: 'LS8-0', alg: "U' R U R U' R' F R' F' R U R'" }],
    LS9: [{ name: 'LS9-0', alg: "U2 y' R2 U R' U' R U' R2 F R F'" }],
  },
};

export const BASE_PRESETS = [
  { name: '空', face: '' },
  { name: 'R', face: 'R' },
  { name: 'R U', face: 'R U' },
  { name: "R U R'", face: "R U R'" },
  { name: "R U2 R'", face: "R U2 R'" },
  { name: "F R U R'", face: "F R U R'" },
];
