// �?scripts/genCaseLibrary.mjs 自动生成，请勿手动编�?// 基于 constants.js �?METHOD_DATA
// �?773 条记�?
export const CASE_LIBRARY = {
  EG: {
    'CLL': [
      { name: 'PBL', subcase: 1, alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
      { name: 'PBL', subcase: 2, alg: "R U R' F' R U R' U' R' F R2 U' R'" },
      { name: 'PBL', subcase: 3, alg: "U2 R U R' F' R U R' U' R' F R2 U' R'" },
      { name: 'PBL', subcase: 4, alg: "U' R U R' F' R U R' U' R' F R2 U' R'" },
      { name: 'PBL', subcase: 5, alg: "U R U R' F' R U R' U' R' F R2 U' R'" },
      { name: 'Sune', subcase: 0, alg: "R U R' U R U2 R'" },
      { name: 'Sune', subcase: 1, alg: "U' R' F R2 F' U' R' U' R2 U R'" },
      { name: 'Sune', subcase: 2, alg: "F R' F' R U2 R U2 R'" },
      { name: 'Sune', subcase: 3, alg: "R U' R' F R' F' R" },
      { name: 'Sune', subcase: 4, alg: "U2 R U' R U' R' U R' U' F R' F'" },
      { name: 'Sune', subcase: 5, alg: "R' F2 R U2 R U' R' F" },
      { name: 'Anti-Sune', subcase: 0, alg: "R' U' R U' R' U2 R" },
      { name: 'Anti-Sune', subcase: 1, alg: "R U2 R' F R' F' R U' R U' R'" },
      { name: 'Anti-Sune', subcase: 2, alg: "U2 F' R U R' U2 R' F2 R" },
      { name: 'Anti-Sune', subcase: 3, alg: "U2 R' F R F' R U R'" },
      { name: 'Anti-Sune', subcase: 4, alg: "U2 R U2 R' U2 R' F R F'" },
      { name: 'Anti-Sune', subcase: 5, alg: "U R U R2 F' R F R U' R2 F R" },
      { name: 'Pi', subcase: 0, alg: "R U' R2 U R2 U R2 U' R" },
      { name: 'Pi', subcase: 1, alg: "U' R' U' R' F R F' R U' R' U2 R" },
      { name: 'Pi', subcase: 2, alg: "U' R U' R U' R' U R' F R2 F'" },
      { name: 'Pi', subcase: 3, alg: "U2 R' F R F' R U' R' U' R U' R'" },
      { name: 'Pi', subcase: 4, alg: "R U2 R' U' R U R' U2 R' F R F'" },
      { name: 'Pi', subcase: 5, alg: "U F R' F' R U2 R U' R' U R U2 R'" },
      { name: 'U', subcase: 0, alg: "U R' U' R2 U R' U2 R U2 R' U R'" },
      { name: 'U', subcase: 1, alg: "F R U R' U' F'" },
      { name: 'U', subcase: 2, alg: "F R' F' R U' R U' R' U2 R U' R'" },
      { name: 'U', subcase: 3, alg: "U' F R U R' U2 F' R U' R' F" },
      { name: 'U', subcase: 4, alg: "U R U' R2 F R F' R U R' U' R U R'" },
      { name: 'U', subcase: 5, alg: "U R' U R' F R F' R U2 R' U R" },
      { name: 'L', subcase: 0, alg: "U R' U R' U2 R U' R' U R U' R2" },
      { name: 'L', subcase: 1, alg: "R U2 R2 F R F' R U2 R'" },
      { name: 'L', subcase: 2, alg: "F R' F' R U R U' R'" },
      { name: 'L', subcase: 3, alg: "U' R U' R' U R U' R' F R' F' R2 U R'" },
      { name: 'L', subcase: 4, alg: "F R U' R' U' R U R' F'" },
      { name: 'L', subcase: 5, alg: "R' U' R U2 R' F R' F' R U' R" },
      { name: 'T', subcase: 0, alg: "U' R' U R' U2 R U2 R' U R2 U' R'" },
      { name: 'T', subcase: 1, alg: "U F U' R U2 R' U' F2 R U R'" },
      { name: 'T', subcase: 2, alg: "U2 R U R' U2 R U R' U R' F R F'" },
      { name: 'T', subcase: 3, alg: "U R' U R U2 R2 F R F' R" },
      { name: 'T', subcase: 4, alg: "R U R' U' R' F R F'" },
      { name: 'T', subcase: 5, alg: "U2 R' F' R U R U' R' F" },
      { name: 'H', subcase: 0, alg: "R2 U2 R' U2 R2" },
      { name: 'H', subcase: 1, alg: "U R U' R' F R' F' R2 U' R' F R' F' R" },
      { name: 'H', subcase: 2, alg: "U' F R2 U' R2 U' R2 U R2 F'" },
      { name: 'H', subcase: 3, alg: "U F R2 U' R2 U' R2 U R2 F'" },
      { name: 'H', subcase: 4, alg: "U' R U R' U R U R' F R' F' R" },
      { name: 'H', subcase: 5, alg: "U R U R' U R U R' F R' F' R" }
    ],
    'EG-1': [
      { name: 'PBL', subcase: 0, alg: "y' R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
      { name: 'PBL', subcase: 1, alg: "R U' R' U' R' F2 U' R U R" },
      { name: 'PBL', subcase: 2, alg: "U R2 U' R2 U2 F2 U' R2" },
      { name: 'PBL', subcase: 3, alg: "U' R2 U' R2 U2 F2 U' R2" },
      { name: 'PBL', subcase: 4, alg: "R2 U' R2 U2 F2 U' R2" },
      { name: 'PBL', subcase: 5, alg: "U2 R2 U' R2 U2 F2 U' R2" },
      { name: 'Sune', subcase: 0, alg: "U2 R U R' U F R U' R2 F' R" },
      { name: 'Sune', subcase: 1, alg: "R U R' F2 U F R U R'" },
      { name: 'Sune', subcase: 2, alg: "U2 F R' F' R U R' F' R2 U R'" },
      { name: 'Sune', subcase: 3, alg: "F' U R U' R' U F R U R'" },
      { name: 'Sune', subcase: 4, alg: "R U' R' U R U' R' U F R U' R'" },
      { name: 'Sune', subcase: 5, alg: "R' F R2 U' R' U R U' R' F" },
      { name: 'Anti-Sune', subcase: 0, alg: "U R' F R2 U R' F' U' R U' R'" },
      { name: 'Anti-Sune', subcase: 1, alg: "U R U' R' F' U' F2 R U' R'" },
      { name: 'Anti-Sune', subcase: 2, alg: "F' R U R' U' R U R2 F' R" },
      { name: 'Anti-Sune', subcase: 3, alg: "R U' R' F' U' R U R' U' F" },
      { name: 'Anti-Sune', subcase: 4, alg: "U2 R U' R2 F R U' R' F R F'" },
      { name: 'Anti-Sune', subcase: 5, alg: "U' R U R' F' U' R U R' U' R U R'" },
      { name: 'Pi', subcase: 0, alg: "U2 F2 R U R' U2 R U R' U' F" },
      { name: 'Pi', subcase: 1, alg: "U' R U' R2 F R2 U' R'" },
      { name: 'Pi', subcase: 2, alg: "U' R U' R' U R U' R' F R U' R'" },
      { name: 'Pi', subcase: 3, alg: "U' F R' F U' F2 R U R" },
      { name: 'Pi', subcase: 4, alg: "U F U' R U2 R' F' R U R' F'" },
      { name: 'Pi', subcase: 5, alg: "F R U' R' F R U2 R' U F'" },
      { name: 'U', subcase: 0, alg: "U' y R' U R' U' R U' R' U' F2 R2" },
      { name: 'U', subcase: 1, alg: "R U R' U R U R2 F R2 U' R'" },
      { name: 'U', subcase: 2, alg: "U2 R' F R F' R' F R2 U' R'" },
      { name: 'U', subcase: 3, alg: "U F' U2 R U2 R' U2 F" },
      { name: 'U', subcase: 4, alg: "U2 R' F R F' U R U' R' F R U' R'" },
      { name: 'U', subcase: 5, alg: "U' R' F R U' R' F R U' R U R' F'" },
      { name: 'L', subcase: 0, alg: "R' F R2 U R' F' R U2 R'" },
      { name: 'L', subcase: 1, alg: "R' U R2 U' R2 U' F R2 U' R'" },
      { name: 'L', subcase: 2, alg: "U2 R' F R F' R' F R U R U2 R'" },
      { name: 'L', subcase: 3, alg: "U R U R' F' R U R' U' F R' F' R" },
      { name: 'L', subcase: 4, alg: "R U' R' U R U' R2 F' R F" },
      { name: 'L', subcase: 5, alg: "U R' U2 F R U2 R U' R2 F" },
      { name: 'T', subcase: 0, alg: "R2 B2 U' R' U' R U' R' U R'" },
      { name: 'T', subcase: 1, alg: "R' F R2 U' R' U' R' F2 R" },
      { name: 'T', subcase: 2, alg: "U2 R U R2 F' R F R' F' R" },
      { name: 'T', subcase: 3, alg: "U' R U' R' U2 F R U2 R' F" },
      { name: 'T', subcase: 4, alg: "U F R U' R2 F' R U R' F' R" },
      { name: 'T', subcase: 5, alg: "U F' R' F R2 U R' U' R U R'" },
      { name: 'H', subcase: 0, alg: "R' F R2 U' R2 U' F U R" },
      { name: 'H', subcase: 1, alg: "F' U R U' R2 F2 R U' F" },
      { name: 'H', subcase: 2, alg: "U2 R U R' F' R U R' U' R U R'" },
      { name: 'H', subcase: 3, alg: "R U R' F' R U R' U' R U R'" },
      { name: 'H', subcase: 4, alg: "R' F R F' U2 F R U2 R' F" },
      { name: 'H', subcase: 5, alg: "U2 R' F R F' U2 F R U2 R' F" }
    ],
    'EG-2': [
      { name: 'PBL', subcase: 0, alg: "F R2 U2 R' U R U2 R2 F R F' R' F'" },
      { name: 'PBL', subcase: 1, alg: "R2 F2 R2" },
      { name: 'PBL', subcase: 2, alg: "U R' U R' F2 R F' R" },
      { name: 'PBL', subcase: 3, alg: "U' R' U R' F2 R F' R" },
      { name: 'PBL', subcase: 4, alg: "R' U R' F2 R F' R" },
      { name: 'PBL', subcase: 5, alg: "U2 R' U R' F2 R F' R" },
      { name: 'Sune', subcase: 0, alg: "U' F U' R2 U' R' U2 R U' R2 F'" },
      { name: 'Sune', subcase: 1, alg: "R U R' U R U2 R B2 R2" },
      { name: 'Sune', subcase: 2, alg: "R U' R' F R' F' R' F2 R2" },
      { name: 'Sune', subcase: 3, alg: "U F R2 F' R2 F' R U' R" },
      { name: 'Sune', subcase: 4, alg: "F' R' U R' U2 F R' U R'" },
      { name: 'Sune', subcase: 5, alg: "R2 B2 R' U' R' F R' F' R" },
      { name: 'Anti-Sune', subcase: 0, alg: "U2 R' U R U' R2 F R F' R U R' U' R' F2 R2" },
      { name: 'Anti-Sune', subcase: 1, alg: "R' U' R U' R' U2 R' F2 R2" },
      { name: 'Anti-Sune', subcase: 2, alg: "U2 R' F R F' R U R B2 R2" },
      { name: 'Anti-Sune', subcase: 3, alg: "R' U2 R U' R2 F' R U' F R" },
      { name: 'Anti-Sune', subcase: 4, alg: "U2 R2 F2 R F R F' R U R'" },
      { name: 'Anti-Sune', subcase: 5, alg: "R2 B2 R2 F' R U R' U2 R' F2 R" },
      { name: 'Pi', subcase: 0, alg: "F U' R U2 R U' R' U R' F'" },
      { name: 'Pi', subcase: 1, alg: "R' U2 R2 U' R' F2 R2 F'" },
      { name: 'Pi', subcase: 2, alg: "U R' F U' R U R' F2 U2 R" },
      { name: 'Pi', subcase: 3, alg: "U2 R' F' U R' F R2 U2 R' U R" },
      { name: 'Pi', subcase: 4, alg: "U R' U' R' F2 R2 U R' F2 R" },
      { name: 'Pi', subcase: 5, alg: "U R' U2 R U' R2 F2 R F R" },
      { name: 'U', subcase: 0, alg: "F R U R' U' F R2 B2" },
      { name: 'U', subcase: 1, alg: "F U' R U2 R U' R' U2 R' U' F'" },
      { name: 'U', subcase: 2, alg: "U2 R' U R' F' R U' R U R' F2 R" },
      { name: 'U', subcase: 3, alg: "U' R' U' R U R' F2 R U' R' U R" },
      { name: 'U', subcase: 4, alg: "U' R U' R' U2 R B R' U2 R U' R'" },
      { name: 'U', subcase: 5, alg: "U' R' F R U2 R' U' R U2 R' F R" },
      { name: 'L', subcase: 0, alg: "U2 R' U' R U R' F' R U R' U' R' F' R2" },
      { name: 'L', subcase: 1, alg: "R' U' F2 R U2 R' U2 F R" },
      { name: 'L', subcase: 2, alg: "U R2 B2 R' U R U' R' F R' F'" },
      { name: 'L', subcase: 3, alg: "F R' F' R U R U' R B2 R2" },
      { name: 'L', subcase: 4, alg: "R' U' R' F' R U' R U' R' F R" },
      { name: 'L', subcase: 5, alg: "U F' R U R' U' R' F R' F2 R2" },
      { name: 'T', subcase: 0, alg: "U' R2 B2 R2 F R U R' U' F'" },
      { name: 'T', subcase: 1, alg: "U R' U R U2 R2 F' R U' R" },
      { name: 'T', subcase: 2, alg: "U R' U R U2 R2 F R F' R' F2 R2" },
      { name: 'T', subcase: 3, alg: "U2 R' U2 R' F2 R F2 R" },
      { name: 'T', subcase: 4, alg: "F R F' R U R' U' R B2 R2" },
      { name: 'T', subcase: 5, alg: "R U R' U' R' F R F' R2 B2 R2" },
      { name: 'H', subcase: 0, alg: "U R2 F U2 F2 R2 F' R2" },
      { name: 'H', subcase: 1, alg: "R2 U2 R' U2 F2 R2" },
      { name: 'H', subcase: 2, alg: "U2 R U2 B2 R' U R U' B R'" },
      { name: 'H', subcase: 3, alg: "R U2 B2 R' U R U' B R'" },
      { name: 'H', subcase: 4, alg: "U' R' U' R U2 R2 F' R U' F R" },
      { name: 'H', subcase: 5, alg: "U R' U' R U2 R2 F' R U' F R" }
    ],
    'LEG-1': [
      { name: 'PBL', subcase: 0, alg: "R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
      { name: 'PBL', subcase: 1, alg: "R2 U R2 U' R2 U R2 U' R2" },
      { name: 'PBL', subcase: 2, alg: "F2 U' R2 U2 B2 U' R2" },
      { name: 'PBL', subcase: 3, alg: "U2 F2 U' R2 U2 B2 U' R2" },
      { name: 'PBL', subcase: 4, alg: "U' F2 U' R2 U2 B2 U' R2" },
      { name: 'PBL', subcase: 5, alg: "U F2 U' R2 U2 B2 U' R2" },
      { name: 'Sune', subcase: 0, alg: "U2 R' F U2 R2 F R'" },
      { name: 'Sune', subcase: 1, alg: "U' R U R2 F' U F2 R2 F'" },
      { name: 'Sune', subcase: 2, alg: "U2 F R' F' R2 U2 R U' R2" },
      { name: 'Sune', subcase: 3, alg: "U R2 U' R2 F' R U2 R' U2 R' F" },
      { name: 'Sune', subcase: 4, alg: "U2 F2 R F' U R' F U' R2" },
      { name: 'Sune', subcase: 5, alg: "U' R U2 R U' R2 F R2 F'" },
      { name: 'Anti-Sune', subcase: 0, alg: "U2 x' R U' R2 U R2 B2 R'" },
      { name: 'Anti-Sune', subcase: 1, alg: "U R2 U R2 U' R U2 R' U' R U R'" },
      { name: 'Anti-Sune', subcase: 2, alg: "U' F R2 F' R2 U R' U2 R'" },
      { name: 'Anti-Sune', subcase: 3, alg: "U' F' R U2 R U2 R' F R2 U R2" },
      { name: 'Anti-Sune', subcase: 4, alg: "U2 R2 U R' U2 R2 F R F'" },
      { name: 'Anti-Sune', subcase: 5, alg: "U2 R2 U R2 U2 R' F R F' R U' R'" },
      { name: 'Pi', subcase: 0, alg: "U' R F R' F' U R U' R2 F R F'" },
      { name: 'Pi', subcase: 1, alg: "U' R U R' U' R U2 R U' R2" },
      { name: 'Pi', subcase: 2, alg: "U' R2 U R' F R F' U R'" },
      { name: 'Pi', subcase: 3, alg: "U2 R F' U R' F2 U R F" },
      { name: 'Pi', subcase: 4, alg: "U R U' R' F R F' R2 U2 R" },
      { name: 'Pi', subcase: 5, alg: "U R U R' U R2 U' R2 F R2 F'" },
      { name: 'U', subcase: 0, alg: "U' R F R' F' R U' R' F' U' F" },
      { name: 'U', subcase: 1, alg: "R U' R U R' U R U R2" },
      { name: 'U', subcase: 2, alg: "U' F' U' F R2 U' R' U R U' R'" },
      { name: 'U', subcase: 3, alg: "R2 U2 R' U' R' F R F' U R'" },
      { name: 'U', subcase: 4, alg: "U' R2 U R' U2 R' F' U' F" },
      { name: 'U', subcase: 5, alg: "U R2 U' R U2 R F R F'" },
      { name: 'L', subcase: 0, alg: "R' F U2 R2 F R U2 R U2 R2" },
      { name: 'L', subcase: 1, alg: "R' U R' U R2 U' R U2 R'" },
      { name: 'L', subcase: 2, alg: "U2 R U' R' U' R2 U' R2 F R F'" },
      { name: 'L', subcase: 3, alg: "F' U F R U2 R U' R2" },
      { name: 'L', subcase: 4, alg: "U' R U2 F R' F' R U2 R U R2" },
      { name: 'L', subcase: 5, alg: "U2 R' U2 R' F R2 F' U' R" },
      { name: 'T', subcase: 0, alg: "U F R F' R' F R2 F' U R' U R" },
      { name: 'T', subcase: 1, alg: "U2 R U2 R' U2 R U2 R U' R2" },
      { name: 'T', subcase: 2, alg: "U2 R U R' U' R U R2 F' U F" },
      { name: 'T', subcase: 3, alg: "U' R' F R2 F' R' U2 F R F'" },
      { name: 'T', subcase: 4, alg: "U R U R' U' F' R' U2 R U' F" },
      { name: 'T', subcase: 5, alg: "U R U' F R2 F' U R U' R2" },
      { name: 'H', subcase: 0, alg: "R F2 R F' R' F U' F" },
      { name: 'H', subcase: 1, alg: "R2 U' R U' R' U R' U' R U' R2" },
      { name: 'H', subcase: 2, alg: "U2 R U2 R U' F R F' R" },
      { name: 'H', subcase: 3, alg: "R U2 R U' F R F' R" },
      { name: 'H', subcase: 4, alg: "U2 R2 B2 R' U R' F' R U R' U' R U R'" },
      { name: 'H', subcase: 5, alg: "R2 B2 R' U R' F' R U R' U' R U R'" }
    ]
  },
  LS: {
    'LS1': [
      { name: 'PBL', subcase: 0, alg: "F2 R2 U' R' F R' F2 R U' R'" },
      { name: 'PBL', subcase: 1, alg: "U2 R' F R F' R' F R F' R' F R F'" },
      { name: 'PBL', subcase: 2, alg: "U R' F R F' U R U2 R'" },
      { name: 'PBL', subcase: 3, alg: "U2 R U' R U' R' F R' F' R U R'" },
      { name: 'PBL', subcase: 4, alg: "U2 R U' R' U2 R U R'" },
      { name: 'PBL', subcase: 5, alg: "R U' R' F R F' R U R' U R'" },
      { name: 'Sune', subcase: 0, alg: "y' U2 R' U2 R U' F R2 F'" },
      { name: 'Sune', subcase: 1, alg: "U2 R U R' U2 F R' F' R2 U R'" },
      { name: 'Sune', subcase: 2, alg: "y R' F2 R U2 R' F R U' R' F R" },
      { name: 'Sune', subcase: 3, alg: "U' F R' F' R U F R' F' R" },
      { name: 'Sune', subcase: 4, alg: "U' R U' R2 F R F' R' F R F'" },
      { name: 'Sune', subcase: 5, alg: "U F R' F' R U' F R' F' R" },
      { name: 'Anti-Sune', subcase: 0, alg: "U2 R U2 R' U y' R' U2 R" },
      { name: 'Anti-Sune', subcase: 1, alg: "R U' R2 F R F' U2 R U' R' " },
      { name: 'Anti-Sune', subcase: 2, alg: "U' R U' R' U2 R U' R2 F R F'" },
      { name: 'Anti-Sune', subcase: 3, alg: "U' R' F R F' U R' F R F'" },
      { name: 'Anti-Sune', subcase: 4, alg: "R U2 R' U2 R U' R' U R U' R'" },
      { name: 'Anti-Sune', subcase: 5, alg: "U R' F R F' U' R' F R F'" },
      { name: 'U-A', subcase: 0, alg: "U y R' F R U R' F R2 U' R' F" },
      { name: 'U-A', subcase: 1, alg: "U' R2 F R F' R U' R' U R' " },
      { name: 'U-A', subcase: 2, alg: "U' F2 U' R' U R' F' R2" },
      { name: 'U-A', subcase: 3, alg: "U2 F' R U2 R' F U2 R' F R" },
      { name: 'U-A', subcase: 4, alg: "U' R U' R' U R U' R' U R U' R'  " },
      { name: 'U-A', subcase: 5, alg: "U' F' R2 F' R2 F R2" },
      { name: 'U-B', subcase: 0, alg: "U' R U' R' U' R U' R2 F R F'" },
      { name: 'U-B', subcase: 1, alg: "U2 R U' F R' F' R U R' U' R2" },
      { name: 'U-B', subcase: 2, alg: "U y R' F R U' R' F R U' R' F R" },
      { name: 'U-B', subcase: 3, alg: "U R F2 R F2 R' F2" },
      { name: 'U-B', subcase: 4, alg: "U2 R U' R U R' U R U2 R2" },
      { name: 'U-B', subcase: 5, alg: "U R2 F R F' U R U2 R' U2 R'" },
      { name: 'L-A', subcase: 0, alg: "U R U' R2 F R F' R U' R'" },
      { name: 'L-A', subcase: 1, alg: "U R U' R' U2 R U2 R2 F R F' " },
      { name: 'L-A', subcase: 2, alg: "U2 R U R' U' F R' F' R2 U R'" },
      { name: 'L-A', subcase: 3, alg: "U R2 F' R U' F U R' F" },
      { name: 'L-A', subcase: 4, alg: "U2 R2 F' R U' R' F2 R2 U' R2" },
      { name: 'L-A', subcase: 5, alg: "y' U R U2 R U2 R' U2 F R F'" },
      { name: 'L-B', subcase: 0, alg: "U2 R U R' F R' F' R2 U R'" },
      { name: 'L-B', subcase: 1, alg: "U' R U2 R' F' U' F" },
      { name: 'L-B', subcase: 2, alg: "R U' R2 F R F' U R' F R F'" },
      { name: 'L-B', subcase: 3, alg: "U' R U R' F R F' R U R2" },
      { name: 'L-B', subcase: 4, alg: "U' R U R' F' R U' R' F2" },
      { name: 'L-B', subcase: 5, alg: "y R' F2 R U2 R' F R2 U' R' F" },
      { name: 'T-A', subcase: 0, alg: "U' R U2 R' U R U2 R' F R' F' R" },
      { name: 'T-A', subcase: 1, alg: "U y R' F R U' R' F R2 U' R' F" },
      { name: 'T-A', subcase: 2, alg: "y' U2 R' U2 R' F R F' R U R' U' R" },
      { name: 'T-A', subcase: 3, alg: "U' R U' R2 F R F' U R U' R'" },
      { name: 'T-A', subcase: 4, alg: "U' R U2 R' U2 R U2 R'" },
      { name: 'T-A', subcase: 5, alg: "U' x U2 R U2 R' U2 R'" },
      { name: 'T-B', subcase: 0, alg: "U' F R' F' R2 U' R' U R U R' " },
      { name: 'T-B', subcase: 1, alg: "U' R U' R' U R U' R2 F R F'" },
      { name: 'T-B', subcase: 2, alg: "U y R' F2 R U2 R' F2 R" },
      { name: 'T-B', subcase: 3, alg: "U x R2 U' R2 U R2 U x'" },
      { name: 'T-B', subcase: 4, alg: "U R U2 R' U2 R U2 R' U R U' R' " },
      { name: 'T-B', subcase: 5, alg: "U2 R2 U' R' F R' F' R U' R'" }
    ],
    'LS2': [
      { name: 'Hammer', subcase: 0, alg: "U F2 U R U R' U2 F2 R U' R'" },
      { name: 'Hammer', subcase: 1, alg: "U' R U2 R' U R2 U' R' F R' F'" },
      { name: 'Hammer', subcase: 2, alg: "U2 R' U' R U' R2 U2 F R F'" },
      { name: 'Hammer', subcase: 3, alg: "U' R U R' U R' F R F' R U' R'" },
      { name: 'Hammer', subcase: 4, alg: "R U2 R2 F R F' R' F R F'" },
      { name: 'Hammer', subcase: 5, alg: "U2 R' F R F' R U' R2 F R F'" },
      { name: 'Spaceship', subcase: 0, alg: "U y' R2 U R' U2 R U' F R F' R" },
      { name: 'Spaceship', subcase: 1, alg: "R U R' U R U2 R' F R' F' R" },
      { name: 'Spaceship', subcase: 2, alg: "U2 y' R2 U' R2 U' R' U2 R2" },
      { name: 'Spaceship', subcase: 3, alg: "U' R F R F' U R'" },
      { name: 'Spaceship', subcase: 4, alg: "R U R' U2 R U2 R'" },
      { name: 'Spaceship', subcase: 5, alg: "y R U' R' F R' F' R2 U' R' F" },
      { name: 'Stollery-A', subcase: 0, alg: "R U R' F' U' F" },
      { name: 'Stollery-A', subcase: 1, alg: "U R U R' U' R U R2 F R F'" },
      { name: 'Stollery-A', subcase: 2, alg: "F R F' R U R2" },
      { name: 'Stollery-A', subcase: 3, alg: "y R U' R' F R' F' R U' R' F R" },
      { name: 'Stollery-A', subcase: 4, alg: "F' R U' R' F2" },
      { name: 'Stollery-A', subcase: 5, alg: "R' F R F' R U R' U2 R U2 R'" },
      { name: 'Stollery-B', subcase: 0, alg: "U' R' U R2 U R2 U' F R F'" },
      { name: 'Stollery-B', subcase: 1, alg: "R2 U R F R' F' R2" },
      { name: 'Stollery-B', subcase: 2, alg: "y' U R U' R' U' R' U R'" },
      { name: 'Stollery-B', subcase: 3, alg: "R2 U R2 F R F' R' U' R" },
      { name: 'Stollery-B', subcase: 4, alg: "R U' R' U F' R U' R' F2" },
      { name: 'Stollery-B', subcase: 5, alg: "U' F' R F2 R F2 R' F" },
      { name: 'Stollery-C', subcase: 0, alg: "U' R2 U R' U' R' F R F' U R'" },
      { name: 'Stollery-C', subcase: 1, alg: "U2 F' U F U' R U' R'" },
      { name: 'Stollery-C', subcase: 2, alg: "R U' F R F' U R'" },
      { name: 'Stollery-C', subcase: 3, alg: "F R' F' R2 U R2 F R F'" },
      { name: 'Stollery-C', subcase: 4, alg: "R U R' U R U' R'" },
      { name: 'Stollery-C', subcase: 5, alg: "y' R' U R U' R' F R' F' R2" },
      { name: 'Two-Face', subcase: 0, alg: "y R' F2 R U' R' F R2 U' R' F " },
      { name: 'Two-Face', subcase: 1, alg: "U R U R2 F R F' U R U2 R'" },
      { name: 'Two-Face', subcase: 2, alg: "R2 F2 U' R U R' U F2 R2" },
      { name: 'Two-Face', subcase: 3, alg: "U R' F R F' R U R2 F R F' R U2 R'" },
      { name: 'Two-Face', subcase: 4, alg: "U2 R U2 R' U' R U R'" },
      { name: 'Two-Face', subcase: 5, alg: "U2 y' R' U' R' F R F' U2 R" },
      { name: 'Turtle', subcase: 0, alg: "U y R U' R' F U2 R' F R" },
      { name: 'Turtle', subcase: 1, alg: "y R U2 R' U2 R' F R U2 F'" },
      { name: 'Turtle', subcase: 2, alg: "U y R' F R U2 R' F R U' R' F R" },
      { name: 'Turtle', subcase: 3, alg: "U R U2 R' U' R U R2 F R F'" },
      { name: 'Turtle', subcase: 4, alg: "U R U R' U' F' R U' R' F2" },
      { name: 'Turtle', subcase: 5, alg: "F R' F' R2 U R' U R U' R'" },
      { name: 'Gun-A', subcase: 0, alg: "R U R' U R2 U' R' F R' F'" },
      { name: 'Gun-A', subcase: 1, alg: "U R F R' F' R2 U' R' U R" },
      { name: 'Gun-A', subcase: 2, alg: "U R' F R F' R U' R'" },
      { name: 'Gun-A', subcase: 3, alg: "U' R U2 R2 F R F'" },
      { name: 'Gun-A', subcase: 4, alg: "U2 R2 U' R2 U R' U R' U R2" },
      { name: 'Gun-A', subcase: 5, alg: "U2 F' U F U2 R' F R F'" },
      { name: 'Gun-B', subcase: 0, alg: "R U R' U' R U' R' U R' F R F'" },
      { name: 'Gun-B', subcase: 1, alg: "U' F2 R U R U2 R U2 R2 F" },
      { name: 'Gun-B', subcase: 2, alg: "y' U' R U' R2 U R2 U R'" },
      { name: 'Gun-B', subcase: 3, alg: "U2 R2 U2 R U2 R' F R F' R'" },
      { name: 'Gun-B', subcase: 4, alg: "R U R' U2 F2 R U R' F " },
      { name: 'Gun-B', subcase: 5, alg: "U R' F' R U' F R' F2 R" }
    ],
    'LS3': [
      { name: 'Hammer', subcase: 0, alg: "U R' F2 R F' R U R2 F' R F'" },
      { name: 'Hammer', subcase: 1, alg: "R U2 R' U R' F R F' U R U' R'" },
      { name: 'Hammer', subcase: 2, alg: "F R F' R U' R' U2 R2" },
      { name: 'Hammer', subcase: 3, alg: "U2 y R U' R' F R' F R2 U' R' F" },
      { name: 'Hammer', subcase: 4, alg: "U R' F R F' R U R' U2 R' F R F'" },
      { name: 'Hammer', subcase: 5, alg: "U y R' F' R U' R U' R' F R' F R" },
      { name: 'Spaceship', subcase: 0, alg: "U' R2 U' R' U2 R U' F R F' R" },
      { name: 'Spaceship', subcase: 1, alg: "R U2 R' U' R U' R2 F R F'" },
      { name: 'Spaceship', subcase: 2, alg: "U y R' F2 R U' R' F R" },
      { name: 'Spaceship', subcase: 3, alg: "R' F R F' R U R2 F R F'" },
      { name: 'Spaceship', subcase: 4, alg: "U2 R2 U R2 U R U2 R2" },
      { name: 'Spaceship', subcase: 5, alg: "U F' R' F' R U' F" },
      { name: 'Stollery-A', subcase: 0, alg: "U y' R' F R F' U' R' U' R2" },
      { name: 'Stollery-A', subcase: 1, alg: "U2 y' R' U R' F R F' R" },
      { name: 'Stollery-A', subcase: 2, alg: "y' R' U' R U' R' U R" },
      { name: 'Stollery-A', subcase: 3, alg: "R U' R' U R U R2 F R F'" },
      { name: 'Stollery-A', subcase: 4, alg: "F' U R' F' R U' F" },
      { name: 'Stollery-A', subcase: 5, alg: "U R U' R2 F' R U' F R' F2 R" },
      { name: 'Stollery-B', subcase: 0, alg: "U' R U' R' U R' F R F' U R U' R'" },
      { name: 'Stollery-B', subcase: 1, alg: "R U' R U R' U' R' F R F' U R'" },
      { name: 'Stollery-B', subcase: 2, alg: "R2 U R2 U2 R' U R' F R F' R" },
      { name: 'Stollery-B', subcase: 3, alg: "R U' R' U R U' F R F' U R'" },
      { name: 'Stollery-B', subcase: 4, alg: "U' R' U R' U R U' R" },
      { name: 'Stollery-B', subcase: 5, alg: "U R U2 R2 F' R U' F R' F2 R" },
      { name: 'Stollery-C', subcase: 0, alg: "F' U' F R U R'" },
      { name: 'Stollery-C', subcase: 1, alg: "F2 R U' R' F2 U2 R' F R" },
      { name: 'Stollery-C', subcase: 2, alg: "R U R2 F R F'" },
      { name: 'Stollery-C', subcase: 3, alg: "R U' R' U2 R' F R F' R U' R'" },
      { name: 'Stollery-C', subcase: 4, alg: "U' F' R U' R' F2 R U R'" },
      { name: 'Stollery-C', subcase: 5, alg: "R' F R F' R U R' U R U' R'" },
      { name: 'Two-Face', subcase: 0, alg: "R U2 R' U R U' R2 F R F'" },
      { name: 'Two-Face', subcase: 1, alg: "U R U R2 F R F' R U' R'" },
      { name: 'Two-Face', subcase: 2, alg: "U2 y' R' U2 R U R' U' R" },
      { name: 'Two-Face', subcase: 3, alg: "U2 F U R U' R' F' R U' R'" },
      { name: 'Two-Face', subcase: 4, alg: "U' R U2 R' U2 F2 R U R' F" },
      { name: 'Two-Face', subcase: 5, alg: "U F R' F' R U' R' F R F' R U R' U' R U R'" },
      { name: 'Turtle', subcase: 0, alg: "U' R' F R F' U2 R U' R'" },
      { name: 'Turtle', subcase: 1, alg: "U' y' R' U R' U' F R F' R U R2" },
      { name: 'Turtle', subcase: 2, alg: "U R' F R F' R U R' U' R U' R'" },
      { name: 'Turtle', subcase: 3, alg: "R' U R2 U' R2 F R F' U2 R" },
      { name: 'Turtle', subcase: 4, alg: "U' R U' R' U2 R U' R' U R U' R'" },
      { name: 'Turtle', subcase: 5, alg: "U2 R U' R2 F R F' U2 R U R'" },
      { name: 'Gun-A', subcase: 0, alg: "U R U' R2 F R F' U R U2 R'" },
      { name: 'Gun-A', subcase: 1, alg: "U' R U R' U' R' F R F' U2 R U' R'" },
      { name: 'Gun-A', subcase: 2, alg: "F R' F' R U' R U2 R2 F R F'" },
      { name: 'Gun-A', subcase: 3, alg: "F R' F' R U R' F R F' R U' R'" },
      { name: 'Gun-A', subcase: 4, alg: "U R' U R2 U' R2 U' R" },
      { name: 'Gun-A', subcase: 5, alg: "U' R' U2 R U R' F R F' U R" },
      { name: 'Gun-B', subcase: 0, alg: "U R U R' U' R' F R F' R U R2 F R F'" },
      { name: 'Gun-B', subcase: 1, alg: "U2 R' F' R U R U' R' U2 F" },
      { name: 'Gun-B', subcase: 2, alg: "U F' U' F2 R F' R U R2" },
      { name: 'Gun-B', subcase: 3, alg: "U2 R U' R' U2 F R' F' R" },
      { name: 'Gun-B', subcase: 4, alg: "U' y R U' R' F R' F R" },
      { name: 'Gun-B', subcase: 5, alg: "U y R' F2 R2 U' R' F" }
    ],
    'LS4': [
      { name: 'Sune-A', subcase: 0, alg: "F R U2 R' U R U' R' F" },
      { name: 'Sune-A', subcase: 1, alg: "R U2 R2 F2 R U2 R U' R' F" },
      { name: 'Sune-A', subcase: 2, alg: "R U R' F R' F' R" },
      { name: 'Sune-A', subcase: 3, alg: "U R' F2 R F' U R' F R" },
      { name: 'Sune-A', subcase: 4, alg: "R U' R' U R U2 R'" },
      { name: 'Sune-A', subcase: 5, alg: "R' F R F' U R U2 R' U2 R U' R'" },
      { name: 'Sune-B', subcase: 0, alg: "U2 y' R2 F R F' U R U2 R' U R" },
      { name: 'Sune-B', subcase: 1, alg: "U2 y F' R U' R' U' R U' R'" },
      { name: 'Sune-B', subcase: 2, alg: "U2 y' R U' R2 U' R2 U R'" },
      { name: 'Sune-B', subcase: 3, alg: "y R U' R' F U2 R' F' R" },
      { name: 'Sune-B', subcase: 4, alg: "y R2 F' R U R' F R2 U R' U' R" },
      { name: 'Sune-B', subcase: 5, alg: "U' R F R' F' R U2 R U2 R2" },
      { name: 'Sune-C', subcase: 0, alg: "U' F R' F' R U' R U R' U R U' R'" },
      { name: 'Sune-C', subcase: 1, alg: "R U' R' U R U' R' U' R' F R F'" },
      { name: 'Sune-C', subcase: 2, alg: "F R' F' R U' R U2 R' F R' F' R" },
      { name: 'Sune-C', subcase: 3, alg: "R U' R U' R' F R' F'" },
      { name: 'Sune-C', subcase: 4, alg: "U2 R U R2 F R F' R' F R F'" },
      { name: 'Sune-C', subcase: 5, alg: "F R U2 R2 F R" },
      { name: 'Pi-A', subcase: 0, alg: "U y R' F' R U2 F' R U R'" },
      { name: 'Pi-A', subcase: 1, alg: "U2 y F' R U R2 F' R U' R' F2 R" },
      { name: 'Pi-A', subcase: 2, alg: "U y R' F' R U R' F' R U2 R' F' R" },
      { name: 'Pi-A', subcase: 3, alg: "U2 R' F' R U R' F2 R F2" },
      { name: 'Pi-A', subcase: 4, alg: "U' R U' R2 U' R U' R' U2 R" },
      { name: 'Pi-A', subcase: 5, alg: "U2 y F' R U' R' U2 R' F R F'" },
      { name: 'Pi-B', subcase: 0, alg: "R U2 R' U R U' R' F R' F' R" },
      { name: 'Pi-B', subcase: 1, alg: "U F2 R F2 R' F2 U R'" },
      { name: 'Pi-B', subcase: 2, alg: "U2 y F' R U R' U2 R' F R F' R U R'" },
      { name: 'Pi-B', subcase: 3, alg: "U2 y' R' U2 R' F R F' R U' R' U2 R" },
      { name: 'Pi-B', subcase: 4, alg: "U R U2 R' U2 R U' R'" },
      { name: 'Pi-B', subcase: 5, alg: "F R' F' R2 U' R' U R U2 R'" },
      { name: 'U', subcase: 0, alg: "U' R U' R' U R' F R F' R U R'" },
      { name: 'U', subcase: 1, alg: "U2 F R' F' R2 U' R' U R U' R'" },
      { name: 'U', subcase: 2, alg: "y' R U' R U R' U R'" },
      { name: 'U', subcase: 3, alg: "y' R' F R F' R U' R U2 R'" },
      { name: 'U', subcase: 4, alg: "U' R U R' U' R U' R'" },
      { name: 'U', subcase: 5, alg: "U2 y' R' U' R U' R' F R F' R U R'" },
      { name: 'L', subcase: 0, alg: "U2 y' R' F R' F' R U R U' R' U' R" },
      { name: 'L', subcase: 1, alg: "U' R2 F R F' R' U' R2" },
      { name: 'L', subcase: 2, alg: "U R U' R' U R' F R F'" },
      { name: 'L', subcase: 3, alg: "y2 R B2 U' R' F R' F' R" },
      { name: 'L', subcase: 4, alg: "y R2 F R U' R" },
      { name: 'L', subcase: 5, alg: "U2 F R' F' R2 U' R2 F R F'" },
      { name: 'T', subcase: 0, alg: "R U' R' U' R' F R F'" },
      { name: 'T', subcase: 1, alg: "U y' F R F' U R' U' R" },
      { name: 'T', subcase: 2, alg: "U' R2 U' R' F R' F'" },
      { name: 'T', subcase: 3, alg: "U y' R2 F R F' R U R' U' R" },
      { name: 'T', subcase: 4, alg: "U2 y' R2 F R F' R U' F R F'" },
      { name: 'T', subcase: 5, alg: "U2 R2 F' R U R' U' R' F R2" },
      { name: 'H', subcase: 0, alg: "U y F' R U' R' F U2 R' F R F'" },
      { name: 'H', subcase: 1, alg: "y' R' F2 R U R' U2 F R" },
      { name: 'H', subcase: 2, alg: "U2 y R' F' R U R' U' R U' R' U2 R" },
      { name: 'H', subcase: 3, alg: "U2 R U R' U' R U' R2 F R F'" },
      { name: 'H', subcase: 4, alg: "U2 y R' F' R U' R' F R F' R U R'" },
      { name: 'H', subcase: 5, alg: "y F U' R U' R' F'" }
    ],
    'LS5': [
      { name: 'Hammer-A', subcase: 0, alg: "R' F R2 U2 R' U R U' R' F" },
      { name: 'Hammer-A', subcase: 1, alg: "F' R U2 R' U2 R' F R" },
      { name: 'Hammer-A', subcase: 2, alg: "F2 R U2 R' U2 R' F2 R" },
      { name: 'Hammer-A', subcase: 3, alg: "R' F R F' R U R' F R' F' R" },
      { name: 'Hammer-A', subcase: 4, alg: "U2 F' R U' R' F2 R U' R'" },
      { name: 'Hammer-A', subcase: 5, alg: "R' F R F' R U' R' U R U2 R'" },
      { name: 'Hammer-B', subcase: 0, alg: "U2 R U R2 F R F' U R U' R'" },
      { name: 'Hammer-B', subcase: 1, alg: "y R' F R F' R U R' U2 R' F R" },
      { name: 'Hammer-B', subcase: 2, alg: "U' R U' R' F R' F' R U2 R U2 R'" },
      { name: 'Hammer-B', subcase: 3, alg: "U' R U2 R' F R' F' R" },
      { name: 'Hammer-B', subcase: 4, alg: "R U2 R'" },
      { name: 'Hammer-B', subcase: 5, alg: "U' F U2 R' F' R U' F2" },
      { name: 'Spaceship-A', subcase: 0, alg: "U2 R' U' R U R' F R F' R' U' R2" },
      { name: 'Spaceship-A', subcase: 1, alg: " R' F2 R U' R U2 R' F" },
      { name: 'Spaceship-A', subcase: 2, alg: "U' y' R' U' R U' R' U' R" },
      { name: 'Spaceship-A', subcase: 3, alg: "U' F2 R U2 R U' R' F R'" },
      { name: 'Spaceship-A', subcase: 4, alg: "U' F' R U2 R' F R U2 R' F" },
      { name: 'Spaceship-A', subcase: 5, alg: "R' F R F' R U2 R'" },
      { name: 'Spaceship-B', subcase: 0, alg: "R U R' U' F R' F' R2 U' R'" },
      { name: 'Spaceship-B', subcase: 1, alg: "U2 R' F' R U2 R U2 R' F" },
      { name: 'Spaceship-B', subcase: 2, alg: "y' R2 U' R U R2" },
      { name: 'Spaceship-B', subcase: 3, alg: "U R U R' U R' F R F'" },
      { name: 'Spaceship-B', subcase: 4, alg: "U R U2 R' U' F2 R U R' F" },
      { name: 'Spaceship-B', subcase: 5, alg: "U R' F R F' U' F R' F' R" },
      { name: 'Stollery', subcase: 0, alg: "y' R' U' R U2 R' F R' F' R2" },
      { name: 'Stollery', subcase: 1, alg: "F R' F' R U2 R' F R F'" },
      { name: 'Stollery', subcase: 2, alg: "U2 R' U R' U' R U' F R F'" },
      { name: 'Stollery', subcase: 3, alg: "U R' F2 R F' R' F2 R" },
      { name: 'Stollery', subcase: 4, alg: "U2 R U2 R' U F' R U' R' F2" },
      { name: 'Stollery', subcase: 5, alg: "U' R' F2 R F R' F2 R" },
      { name: 'Pinwheel', subcase: 0, alg: "U2 y' R U' R' F R2 F' R2" },
      { name: 'Pinwheel', subcase: 1, alg: "U' y' F R2 F' R U2 R U2 R'" },
      { name: 'Pinwheel', subcase: 2, alg: "U y R U' R' U2 F U2 F" },
      { name: 'Pinwheel', subcase: 3, alg: "U y' R' F R' F' R2 U R' U' R" },
      { name: 'Pinwheel', subcase: 4, alg: "U' R2 U2 R U2 R' U R'" },
      { name: 'Pinwheel', subcase: 5, alg: "F' U F U' R U2 R'" },
      { name: 'Turtle-A', subcase: 0, alg: "y' F R F' R U2 R U2 R'" },
      { name: 'Turtle-A', subcase: 1, alg: "y' R' U' R2 U' R' F R' F' R" },
      { name: 'Turtle-A', subcase: 2, alg: "U' y' R U' R U2 R' U R'" },
      { name: 'Turtle-A', subcase: 3, alg: "U' y F' R U R' U R U' R' F " },
      { name: 'Turtle-A', subcase: 4, alg: "U2 R' U R' U' R U R' U2 R " },
      { name: 'Turtle-A', subcase: 5, alg: "U2 R F' R U R' U2 R' F2 " },
      { name: 'Turtle-B', subcase: 0, alg: "U2 R' F R2 U' R' F' R' F R" },
      { name: 'Turtle-B', subcase: 1, alg: "R' F2 R F' U R' F2 R F'" },
      { name: 'Turtle-B', subcase: 2, alg: "R U2 R' U2 R' F R F' R U R' " },
      { name: 'Turtle-B', subcase: 3, alg: "R' F' U' F U' R U2 R" },
      { name: 'Turtle-B', subcase: 4, alg: "R' U2 R U' R' U R U' R" },
      { name: 'Turtle-B', subcase: 5, alg: "F R' F' R U' R U' R'" },
      { name: 'Pinwheel-Poser', subcase: 0, alg: "U' y R' F R F' R U R2 F R" },
      { name: 'Pinwheel-Poser', subcase: 1, alg: "U2 y' R U2 R' U2 R' F R2 F'" },
      { name: 'Pinwheel-Poser', subcase: 2, alg: "R' U2 R' U2 F R F'" },
      { name: 'Pinwheel-Poser', subcase: 3, alg: "U R U2 R' U F' U' F" },
      { name: 'Pinwheel-Poser', subcase: 4, alg: "R' F' R U' R' F2 R2 U R'" },
      { name: 'Pinwheel-Poser', subcase: 5, alg: "y' R' U R U' R2 F R F' R" }
    ],
    'LS6': [
      { name: 'Hammer', subcase: 0, alg: "U2 y' R U' R2 U' R F R' F' R" },
      { name: 'Hammer', subcase: 1, alg: "U2 R' F R F'" },
      { name: 'Hammer', subcase: 2, alg: "U y' R' U' R U2 R' U' R" },
      { name: 'Hammer', subcase: 3, alg: "R U2 R2 F R F' R U R'" },
      { name: 'Hammer', subcase: 4, alg: "U2 y F R2 U' R' F R' F2" },
      { name: 'Hammer', subcase: 5, alg: "y R F' U R' F R2 U2 F" },
      { name: 'Spaceship', subcase: 0, alg: "U y F' R U R' U2 R' F R" },
      { name: 'Spaceship', subcase: 1, alg: "y R2 F2 R F' R U R' U2 R" },
      { name: 'Spaceship', subcase: 2, alg: "U2 y R U2 R' U' R U' R2 F2 R" },
      { name: 'Spaceship', subcase: 3, alg: "y' R' F R F' R U R' U2 R' U2 R " },
      { name: 'Spaceship', subcase: 4, alg: "U y R' F R F' R U R2 F' R" },
      { name: 'Spaceship', subcase: 5, alg: "R' F R F' U' R U' R'" },
      { name: 'Two-Face', subcase: 0, alg: "U' R' F R F' U R U R'" },
      { name: 'Two-Face', subcase: 1, alg: "y' R' U2 R' F R F' R U R' U R" },
      { name: 'Two-Face', subcase: 2, alg: "U2 y' R' U' R" },
      { name: 'Two-Face', subcase: 3, alg: "R' U' R2 U' R' U2 F R F'" },
      { name: 'Two-Face', subcase: 4, alg: "U2 y R2 F2 R U' R' F2 R2" },
      { name: 'Two-Face', subcase: 5, alg: "R' F2 R2 U R' F R' F2 R" },
      { name: 'Turtle', subcase: 0, alg: "U' R U R' U2 R' F R F'" },
      { name: 'Turtle', subcase: 1, alg: "y' R' F' R U R' U2 R' F2 R2" },
      { name: 'Turtle', subcase: 2, alg: "U' R U' R2 F R F' R U R'" },
      { name: 'Turtle', subcase: 3, alg: "U y F' R U' R' F R U2 R'" },
      { name: 'Turtle', subcase: 4, alg: "U R U' R' U2 R U' R'" },
      { name: 'Turtle', subcase: 5, alg: "U F U2 R2 F U' R U' R" },
      { name: 'Pinwheel-Poser-A', subcase: 0, alg: "U R U2 R' U R' F R F'" },
      { name: 'Pinwheel-Poser-A', subcase: 1, alg: "R U' R2 F R F' U R U R'" },
      { name: 'Pinwheel-Poser-A', subcase: 2, alg: "U2 y' R' F' R U' R' F2 U2 R" },
      { name: 'Pinwheel-Poser-A', subcase: 3, alg: "y' F R' F' U' R' U' R" },
      { name: 'Pinwheel-Poser-A', subcase: 4, alg: "U2 R' U R' U2 R U R' U2 R" },
      { name: 'Pinwheel-Poser-A', subcase: 5, alg: "F R U2 R2 F' R U R' F R" },
      { name: 'Pinwheel-Poser-B', subcase: 0, alg: "U y' F R' F' U R' U' R" },
      { name: 'Pinwheel-Poser-B', subcase: 1, alg: "R' F R F' U2 R' F R F'" },
      { name: 'Pinwheel-Poser-B', subcase: 2, alg: "y' R U R' U R U2 R2 U' R" },
      { name: 'Pinwheel-Poser-B', subcase: 3, alg: "R U' R' U R U R' F R' F' R" },
      { name: 'Pinwheel-Poser-B', subcase: 4, alg: "y' F U2 R2 F R U2 R2" },
      { name: 'Pinwheel-Poser-B', subcase: 5, alg: "U2 y' R2 U2 R U' R2 F R F' R'" },
      { name: 'Pinwheel-Poser-C', subcase: 0, alg: "U y F' R U R' U R' F2 R" },
      { name: 'Pinwheel-Poser-C', subcase: 1, alg: "U' R2 U R' U2 R' F R' F'" },
      { name: 'Pinwheel-Poser-C', subcase: 2, alg: "y' R' U2 R U R' U' R U R' U' R" },
      { name: 'Pinwheel-Poser-C', subcase: 3, alg: "U2 R' F R2 F' U' R' U' R" },
      { name: 'Pinwheel-Poser-C', subcase: 4, alg: "R U' R' U F2 R U R' F" },
      { name: 'Pinwheel-Poser-C', subcase: 5, alg: "U F' U' F U' R U' R'" },
      { name: 'Gun-A', subcase: 0, alg: "R' U' F R F' R' U' R U2 R" },
      { name: 'Gun-A', subcase: 1, alg: "U2 F' U F U2 R U R'" },
      { name: 'Gun-A', subcase: 2, alg: "U2 R' F R2 U' R' U' R U R' F'" },
      { name: 'Gun-A', subcase: 3, alg: "R' F2 R F' R' F2 R2 U2 R'" },
      { name: 'Gun-A', subcase: 4, alg: "U' R U' R'" },
      { name: 'Gun-A', subcase: 5, alg: "U y R U2 R' F R U2 R2 F' R" },
      { name: 'Gun-B', subcase: 0, alg: "U2 y F' R U' R' F R U2 R2 F R" },
      { name: 'Gun-B', subcase: 1, alg: "U' R' U R U2 R' F R2 F'" },
      { name: 'Gun-B', subcase: 2, alg: "U y' R' U' R' F' R U' R' F2 R2" },
      { name: 'Gun-B', subcase: 3, alg: "U2 y F' R U2 R U' R' F R' F'" },
      { name: 'Gun-B', subcase: 4, alg: "U' y R F' R U R2 U2 F" },
      { name: 'Gun-B', subcase: 5, alg: "U y' R' U' R' F R F' R" }
    ],
    'LS7': [
      { name: 'Antisune-A', subcase: 0, alg: "R' U R U' R2 U' F R F' R" },
      { name: 'Antisune-A', subcase: 1, alg: "F' U2 R U R' U' R' F R" },
      { name: 'Antisune-A', subcase: 2, alg: "U2 y' F' R U' R' F2 R2 U2 R'" },
      { name: 'Antisune-A', subcase: 3, alg: "U y' R2 F R F' U R" },
      { name: 'Antisune-A', subcase: 4, alg: "U' F' R U' R' F2 U2 R U2 R'" },
      { name: 'Antisune-A', subcase: 5, alg: "y' R' U' R' F R F' R U R' U2 R" },
      { name: 'Antisune-B', subcase: 0, alg: "U y' R' F R F' U R U' R U R'" },
      { name: 'Antisune-B', subcase: 1, alg: "U2 F R' F R U R' F R" },
      { name: 'Antisune-B', subcase: 2, alg: "y' R2 U R' U R' U R2 U' R2" },
      { name: 'Antisune-B', subcase: 3, alg: "U2 y R2 U R' U2 R' F2 R F' R'" },
      { name: 'Antisune-B', subcase: 4, alg: "U2 R' U R2 U R2 U' R" },
      { name: 'Antisune-B', subcase: 5, alg: "R' F R F' U2 R U R'" },
      { name: 'Antisune-C', subcase: 0, alg: "y F' R' F2 R U' R' F R F'" },
      { name: 'Antisune-C', subcase: 1, alg: "U R' U2 R U2 R2 F R F' R'" },
      { name: 'Antisune-C', subcase: 2, alg: "y' R' U R U' R' U2 R" },
      { name: 'Antisune-C', subcase: 3, alg: "U R' F R2 F' R U R' U R'" },
      { name: 'Antisune-C', subcase: 4, alg: "R2 U R' U R U2 R2" },
      { name: 'Antisune-C', subcase: 5, alg: "U' y R U2 R' F U' R U' R'" },
      { name: 'Pi-A', subcase: 0, alg: "U' R U R' U2 F R' F' R" },
      { name: 'Pi-A', subcase: 1, alg: "U2 F R' F' R2 U R' U R U2 R'" },
      { name: 'Pi-A', subcase: 2, alg: "U2 y' R2 U R' U R U' R' U R U' R'" },
      { name: 'Pi-A', subcase: 3, alg: "y' R' U R' F R F' R U R' U2 R" },
      { name: 'Pi-A', subcase: 4, alg: "U' R U R' U' R U R' U2 R U R'" },
      { name: 'Pi-A', subcase: 5, alg: "U2 y R U R' U' R U2 R' F2" },
      { name: 'Pi-B', subcase: 0, alg: "y' R' U2 R U R' F R F' R U R'" },
      { name: 'Pi-B', subcase: 1, alg: "U2 F R' F' R U R' U2 R U R' U R" },
      { name: 'Pi-B', subcase: 2, alg: "U' y' R' U2 R U2 R' U R" },
      { name: 'Pi-B', subcase: 3, alg: "U y' R2 F R F' R U' R' U2 R" },
      { name: 'Pi-B', subcase: 4, alg: "y' R2 F R F' U R U' R' U R" },
      { name: 'Pi-B', subcase: 5, alg: "U2 y' R' U' F R' F' R2 U R' U R" },
      { name: 'U', subcase: 0, alg: "U y R' F R U' R U' R' F R' F' R" },
      { name: 'U', subcase: 1, alg: "U' y' R2 F R F' R U' R' U R" },
      { name: 'U', subcase: 2, alg: "U y' R' U' R U R' U R" },
      { name: 'U', subcase: 3, alg: "U2 R U R' U' R U' R' F R' F' R" },
      { name: 'U', subcase: 4, alg: "R' U R' U' R U' R" },
      { name: 'U', subcase: 5, alg: "U' R F' R2 F R2 F R'" },
      { name: 'L', subcase: 0, alg: "y' R U2 R U2 R' F R F'" },
      { name: 'L', subcase: 1, alg: "U y' R2 F' U' F R U R2" },
      { name: 'L', subcase: 2, alg: "R2 B' R' B R'" },
      { name: 'L', subcase: 3, alg: "U2 y' R U2 R' F R F' R U2 R'" },
      { name: 'L', subcase: 4, alg: "U' y R' F R U' R U' R' F" },
      { name: 'L', subcase: 5, alg: "U R2 F R F' R U' R2" },
      { name: 'T', subcase: 0, alg: "U R U' R' F' U F" },
      { name: 'T', subcase: 1, alg: "U' y' R' U' R U' F R F'" },
      { name: 'T', subcase: 2, alg: "U' y' R' U' R U' F R F'" },
      { name: 'T', subcase: 3, alg: "U2 y' R' U' R U R2 F R F' U R" },
      { name: 'T', subcase: 4, alg: "y R' U R' F R U' R' F2 R2" },
      { name: 'T', subcase: 5, alg: "y R U2 R' U2 R U2 R' F2" },
      { name: 'T', subcase: 0, alg: "U' F R' F R F' U2 R U' R' F" },
      { name: 'T', subcase: 1, alg: "R U2 R' F' U2 R U' R' F2" },
      { name: 'T', subcase: 2, alg: "U2 R U R' U R U' R' F R' F' R" },
      { name: 'T', subcase: 3, alg: "F' U R' F R F" },
      { name: 'T', subcase: 4, alg: "U' R U' R' U' R U R' U' R U R'" },
      { name: 'T', subcase: 5, alg: "U2 y R' F' R U R' F R2 U' R' F" }
    ],
    'LS8': [
      { name: 'Hammer', subcase: 0, alg: "U' R U R U' R' F R' F' R U R'" },
      { name: 'Hammer', subcase: 1, alg: "U2 F R' F' R" },
      { name: 'Hammer', subcase: 2, alg: "y R' F R U2 R' F R U2 R' F R" },
      { name: 'Hammer', subcase: 3, alg: "U2 R' F2 R2 U' R' U2 R U' R' F" },
      { name: 'Hammer', subcase: 4, alg: "U' R U R' U2 R U R'" },
      { name: 'Hammer', subcase: 5, alg: "y R' F2 R2 U' R' F R' F' R" },
      { name: 'Spaceship', subcase: 0, alg: "U' F R' F' R U2 R U' R'" },
      { name: 'Spaceship', subcase: 1, alg: "U2 y R' U2 R U' R' F R' F2 R2" },
      { name: 'Spaceship', subcase: 2, alg: "U' R U' R' F R' F' R2 U R'" },
      { name: 'Spaceship', subcase: 3, alg: "U' y' F R F' R' U2 R" },
      { name: 'Spaceship', subcase: 4, alg: "U y F2 R F' R U R2 F'" },
      { name: 'Spaceship', subcase: 5, alg: "U2 R U' R' F R U2 R2 F R" },
      { name: 'Two-Face', subcase: 0, alg: "R U' R' U' F R' F' R" },
      { name: 'Two-Face', subcase: 1, alg: "y R U2 R' U' R U2 R' F U'" },
      { name: 'Two-Face', subcase: 2, alg: "U2 y R' F R F R' F R F2" },
      { name: 'Two-Face', subcase: 3, alg: "y R' F R2 U2 R' F' R U2 R'" },
      { name: 'Two-Face', subcase: 4, alg: "U2 R U R'" },
      { name: 'Two-Face', subcase: 5, alg: "U y F R F' R U R' U2 R' F" },
      { name: 'Turtle', subcase: 0, alg: "U y R' F' R U2 R U' R' F" },
      { name: 'Turtle', subcase: 1, alg: "U' R U2 R' U2 F R F' R U R2" },
      { name: 'Turtle', subcase: 2, alg: "U' y R' F R U2 R' F R" },
      { name: 'Turtle', subcase: 3, alg: "U2 y F R' F' R U2 R U2 R2 F R" },
      { name: 'Turtle', subcase: 4, alg: "U y R' F R2 U' R' F R' F' R" },
      { name: 'Turtle', subcase: 5, alg: "U' y R U2 R' F' R U R' F" },
      { name: 'Pinwheel-Poser-A', subcase: 0, alg: "U' y R' F2 R U' R U' R' F" },
      { name: 'Pinwheel-Poser-A', subcase: 1, alg: "U' R U' R' U' F R' F' R2 U R'" },
      { name: 'Pinwheel-Poser-A', subcase: 2, alg: "U' y R' U' R U' R' U2 F R" },
      { name: 'Pinwheel-Poser-A', subcase: 3, alg: "y F' R' F2 R2 U R' U' R U' R'" },
      { name: 'Pinwheel-Poser-A', subcase: 4, alg: "U2 F' R U' R' F2 U' R U R'" },
      { name: 'Pinwheel-Poser-A', subcase: 5, alg: "U y' R U R U' R' F R F'" },
      { name: 'Pinwheel-Poser-B', subcase: 0, alg: "U' y' R' U R U' F R F'" },
      { name: 'Pinwheel-Poser-B', subcase: 1, alg: "y R U' R' F U2 R U' R' F" },
      { name: 'Pinwheel-Poser-B', subcase: 2, alg: "y' R' U R U' R' U R U' R' U2 R" },
      { name: 'Pinwheel-Poser-B', subcase: 3, alg: "U R' F' R U' R' F R2 U2 R' F'" },
      { name: 'Pinwheel-Poser-B', subcase: 4, alg: "U R' U2 R U' R' U2 R U' R" },
      { name: 'Pinwheel-Poser-B', subcase: 5, alg: "U2 y F' U F U R U2 R' F" },
      { name: 'Pinwheel-Poser-C', subcase: 0, alg: "U' F R' F' R U' R U2 R'" },
      { name: 'Pinwheel-Poser-C', subcase: 1, alg: "U F R F' R U2 R U' R2" },
      { name: 'Pinwheel-Poser-C', subcase: 2, alg: "y' R' U2 F2 R U R' F R" },
      { name: 'Pinwheel-Poser-C', subcase: 3, alg: "U' y' F R F' U R' U R" },
      { name: 'Pinwheel-Poser-C', subcase: 4, alg: "U y R' F R F' R U R' U' R' F R" },
      { name: 'Pinwheel-Poser-C', subcase: 5, alg: "F R' F' U R' U' R U' R" },
      { name: 'Gun-A', subcase: 0, alg: "y' F R F' U' R U2 R' U2 R'" },
      { name: 'Gun-A', subcase: 1, alg: "U2 R U' R' U2 F' U' F" },
      { name: 'Gun-A', subcase: 2, alg: "U y' R' U R" },
      { name: 'Gun-A', subcase: 3, alg: "U' R' F2 R F' R U' R2 F2 R" },
      { name: 'Gun-A', subcase: 4, alg: "U2 y' R2 U2 F R F' U R'" },
      { name: 'Gun-A', subcase: 5, alg: "y R U2 R' F R U2 R2 F2 R" },
      { name: 'Gun-B', subcase: 0, alg: "R' U R' U' F R F' R U R' U2 R" },
      { name: 'Gun-B', subcase: 1, alg: "U' F R2 F' R U2 R' U' R" },
      { name: 'Gun-B', subcase: 2, alg: "U R' U R U2 F R F' R" },
      { name: 'Gun-B', subcase: 3, alg: "U y' R' F R' F' R U R" },
      { name: 'Gun-B', subcase: 4, alg: "U' F2 R U R' F R U R'" },
      { name: 'Gun-B', subcase: 5, alg: "U2 y R U' R' U2 R' F R U2 F" }
    ],
    'LS9': [
      { name: 'Hammer-A', subcase: 0, alg: "U2 y' R2 U R' U' R U' R2 F R F'" },
      { name: 'Hammer-A', subcase: 1, alg: "y F R' F' R U R U' R2 F' R" },
      { name: 'Hammer-A', subcase: 2, alg: "U' y' R U R' U R U2 R' U R' U' R" },
      { name: 'Hammer-A', subcase: 3, alg: "U2 y' R U2 R U' F R' F' R'" },
      { name: 'Hammer-A', subcase: 4, alg: "y R2 F2 R U2 R' F2 R2" },
      { name: 'Hammer-A', subcase: 5, alg: "U2 R U' R2 F R F' R U2 R'" },
      { name: 'Hammer-B', subcase: 0, alg: "U2 y' R' F R U2 R2 F R U R" },
      { name: 'Hammer-B', subcase: 1, alg: "y F' R U' R' U R' F2 R F'" },
      { name: 'Hammer-B', subcase: 2, alg: "F' U2 F" },
      { name: 'Hammer-B', subcase: 3, alg: "R U2 R' F R' F' R2 U R'" },
      { name: 'Hammer-B', subcase: 4, alg: "U' y' R' F R F' R U R2 U2 R" },
      { name: 'Hammer-B', subcase: 5, alg: "U y R' F2 R F' R U R'" },
      { name: 'Spaceship-A', subcase: 0, alg: "y' R' U' R U2 R2 F R F' R" },
      { name: 'Spaceship-A', subcase: 1, alg: "U2 y R U R' U2 R' F2 R F'" },
      { name: 'Spaceship-A', subcase: 2, alg: "U' y R' F U' R U' R' U2 F R" },
      { name: 'Spaceship-A', subcase: 3, alg: "U' F R' F' R U R' F R F'" },
      { name: 'Spaceship-A', subcase: 4, alg: "R U' R' U' R U R'" },
      { name: 'Spaceship-A', subcase: 5, alg: "U' y R' F' R U' R U' R' F" },
      { name: 'Spaceship-B', subcase: 0, alg: "y' F R F' R U R' U R' U2 R'" },
      { name: 'Spaceship-B', subcase: 1, alg: "y R U2 R' U R' F2 R F'" },
      { name: 'Spaceship-B', subcase: 2, alg: "y U R' F U' R U' R' U2 R" },
      { name: 'Spaceship-B', subcase: 3, alg: "y R U' R' F R' F2 R" },
      { name: 'Spaceship-B', subcase: 4, alg: "U R U' R' U R U R'" },
      { name: 'Spaceship-B', subcase: 5, alg: "y R' F2 R F' R U R' U' R' F R" },
      { name: 'Stollery', subcase: 0, alg: "U' R U2 R' U R U2 R2 F R F'" },
      { name: 'Stollery', subcase: 1, alg: "U2 y R U2 R' F2 R U2 R'" },
      { name: 'Stollery', subcase: 2, alg: "F R' F' R U2 R U' R' U2 R' F R F'" },
      { name: 'Stollery', subcase: 3, alg: "U y R U2 R' F' R U2 R'" },
      { name: 'Stollery', subcase: 4, alg: "U' y R' U R U2 R2 F2 R U' R" },
      { name: 'Stollery', subcase: 5, alg: "U' y R U2 R' F R U2 R'" },
      { name: 'Pinwheel', subcase: 0, alg: "U2 R U R2 F R F' R U R'" },
      { name: 'Pinwheel', subcase: 1, alg: "U2 y' R' F R F' R U' R' U2 R'" },
      { name: 'Pinwheel', subcase: 2, alg: "U' y R U2 R' F U2 R' F R F'" },
      { name: 'Pinwheel', subcase: 3, alg: "R U' R' U F' U2 F" },
      { name: 'Pinwheel', subcase: 4, alg: "U2 R U R2 F' R U' R' F2 R" },
      { name: 'Pinwheel', subcase: 5, alg: "U' R U R2 F R F' U2 R U R'" },
      { name: 'Turtle-A', subcase: 0, alg: "R U R' U' R' F R F' R U' R'" },
      { name: 'Turtle-A', subcase: 1, alg: "R U R' U R U2 R2 F R F'" },
      { name: 'Turtle-A', subcase: 2, alg: "U2 y' R U' R U R' U' R U2 R' " },
      { name: 'Turtle-A', subcase: 3, alg: "y' R' U R U' R' U R' F R F' U R" },
      { name: 'Turtle-A', subcase: 4, alg: "U R' U R' U2 R U' R" },
      { name: 'Turtle-A', subcase: 5, alg: "U F R' F' R U' R' F R F'" },
      { name: 'Turtle-B', subcase: 0, alg: "U2 y R U2 R' F' R U2 R2 F R" },
      { name: 'Turtle-B', subcase: 1, alg: "y R U2 R' F U' R U2 R' F" },
      { name: 'Turtle-B', subcase: 2, alg: "y' R U2 R' U R U' R' U R'" },
      { name: 'Turtle-B', subcase: 3, alg: "y F' R U R' U R' F R" },
      { name: 'Turtle-B', subcase: 4, alg: "y' R' U2 R2 U' R' F R' F' R" },
      { name: 'Turtle-B', subcase: 5, alg: "y' R F R F' U R' U2 R'" },
      { name: 'Pinwheel-Poser', subcase: 0, alg: "U R U' R' F R' F' R2 U' R'" },
      { name: 'Pinwheel-Poser', subcase: 1, alg: "U2 y' R U2 R U R' F R' F' R" },
      { name: 'Pinwheel-Poser', subcase: 2, alg: "y R U R' U R U2 R2 F' R" },
      { name: 'Pinwheel-Poser', subcase: 3, alg: "U F R' F' R U R' F R F' R U2 R'" },
      { name: 'Pinwheel-Poser', subcase: 4, alg: "F U2 F U2 R' F' R" },
      { name: 'Pinwheel-Poser', subcase: 5, alg: "F R' F' R U2 R U R'" }
    ]
  },
  TCLL: {
    'TCLL+': [
      { name: 'Hammer', subcase: 0, alg: "R' F R F' R' F R F'" },
      { name: 'Hammer', subcase: 1, alg: "U' y' R' U' R' F R F' R U R' U' R" },
      { name: 'Hammer', subcase: 2, alg: "U y' R' U' R U' R2 F R F' R" },
      { name: 'Hammer', subcase: 3, alg: "U2 R' F' R U2 R U R' F2" },
      { name: 'Hammer', subcase: 4, alg: "U R' U R U' R U' R2 F R2 F'" },
      { name: 'Hammer', subcase: 5, alg: "y' R' U2 R U' F R' F'" },
      { name: 'Spaceship', subcase: 0, alg: "U2 y' R' U' R U R' U' R" },
      { name: 'Spaceship', subcase: 1, alg: "U R' F R F' R' F R U R U' R' F'" },
      { name: 'Spaceship', subcase: 2, alg: "U R U' R' U R2 U' R' F R' F'" },
      { name: 'Spaceship', subcase: 3, alg: "U2 R U' R' F R F' R U R2 U' R U' R'" },
      { name: 'Spaceship', subcase: 4, alg: "U R U2 R' U R' F R F' R U' R'" },
      { name: 'Spaceship', subcase: 5, alg: "U R U' R2 F R U R U' R' F'" },
      { name: 'Stollery', subcase: 0, alg: "R U R' U F' R U' R' F2" },
      { name: 'Stollery', subcase: 1, alg: "U2 R' F R U' F' R U2 R' F2" },
      { name: 'Stollery', subcase: 2, alg: "U R U' R' U' R U' R' U R' F R F'" },
      { name: 'Stollery', subcase: 3, alg: "U' y' R' U2 R U R' U' R' F R F' R" },
      { name: 'Stollery', subcase: 4, alg: "R' U' F R F' U R2 U' R'" },
      { name: 'Stollery', subcase: 5, alg: "R U R' F R' F' R U R U R'" },
      { name: 'Pinwheel', subcase: 0, alg: "y' F' R U R U2 R2 F' U R F'" },
      { name: 'Pinwheel', subcase: 1, alg: "y' R' U' R U R' U2 F R' F' R U R" },
      { name: 'Pinwheel', subcase: 2, alg: "y' U R' F2 R U' R' U2 R' F R2" },
      { name: 'Pinwheel', subcase: 3, alg: "y' U' R' F2 R U' R' U2 R' F R2" },
      { name: 'Pinwheel', subcase: 4, alg: "y' U2 R' F2 R U' R' U2 R' F R2" },
      { name: 'Pinwheel', subcase: 5, alg: "y' U R' F2 R U' R' U2 R' F R2" },
      { name: 'Two-Face', subcase: 0, alg: "U R U R' U' R2 U R2 U' R2" },
      { name: 'Two-Face', subcase: 1, alg: "R U' R' U F' R' F' R F" },
      { name: 'Two-Face', subcase: 2, alg: "y' U' R' U2 R' F R F' R" },
      { name: 'Two-Face', subcase: 3, alg: "y' U R' U2 R' F R F' R" },
      { name: 'Two-Face', subcase: 4, alg: "U' R U R' U2 R' F R F' U R U2 R'" },
      { name: 'Two-Face', subcase: 5, alg: "U R U R' U2 R' F R F' U R U2 R'" },
      { name: 'Turtle', subcase: 0, alg: "R U' R' U R U' R'" },
      { name: 'Turtle', subcase: 1, alg: "y R U' R' F2 R U R' F' R' F R" },
      { name: 'Turtle', subcase: 2, alg: "U F R' F' R U' R' F R F' R U' R'" },
      { name: 'Turtle', subcase: 3, alg: "U2 R' F R F' U2 R U2 R'" },
      { name: 'Turtle', subcase: 4, alg: "U2 R U R2 F R F' U2 R U' R'" },
      { name: 'Turtle', subcase: 5, alg: "U2 y' R' U' R U' F R2 F'" },
      { name: 'Pinwheel-Poser', subcase: 0, alg: "y R U R' U' R U2 R' F' R U R' F'" },
      { name: 'Pinwheel-Poser', subcase: 1, alg: "U' R' F R F' R' F R2 U R' U' F'" },
      { name: 'Pinwheel-Poser', subcase: 2, alg: "R U R' U2 R' F R F' R U' R'" },
      { name: 'Pinwheel-Poser', subcase: 3, alg: "R U' R2 F R F'" },
      { name: 'Pinwheel-Poser', subcase: 4, alg: "U2 F' U R' F2 R F" },
      { name: 'Pinwheel-Poser', subcase: 5, alg: "U2 y F' R U R2 F' R" },
      { name: 'Gun', subcase: 0, alg: "R U' R' U2 R U2 R'" },
      { name: 'Gun', subcase: 1, alg: "U' y F' R' F2 R F' R' F R2 U' R'" },
      { name: 'Gun', subcase: 2, alg: "R' F R F' U R U' R'" },
      { name: 'Gun', subcase: 3, alg: "U2 R U R' U R U R2 F R F'" },
      { name: 'Gun', subcase: 4, alg: "U R U2 R' F R F' R U R2" },
      { name: 'Gun', subcase: 5, alg: "R U' R' U R U2 R' F R' F' R" }
    ],
    'TCLL-': [
      { name: 'Hammer', subcase: 0, alg: "U' F R' F' R F R' F' R" },
      { name: 'Hammer', subcase: 1, alg: "R U' R U' R' F R' F' R U' R'" },
      { name: 'Hammer', subcase: 2, alg: "U' R U R' F R' F' R U' R U2 R'" },
      { name: 'Hammer', subcase: 3, alg: "U' R' F R y' R U' R2 U R2" },
      { name: 'Hammer', subcase: 4, alg: "U' F R U R' U' R' F' R2 U R'" },
      { name: 'Hammer', subcase: 5, alg: "U' R U2 R' y' U R' U R" },
      { name: 'Spaceship', subcase: 0, alg: "R U R' U' R U R'" },
      { name: 'Spaceship', subcase: 1, alg: "U2 F R U R' U' R' F' R F R' F' R" },
      { name: 'Spaceship', subcase: 2, alg: "U' R' F R F' U R U2 R2 F R F'" },
      { name: 'Spaceship', subcase: 3, alg: "U F2 R U' R' U2 R' F R" },
      { name: 'Spaceship', subcase: 4, alg: "U' y R' F U' R' F R2 U' R' U2 R" },
      { name: 'Spaceship', subcase: 5, alg: "U' R U R' F R' F' R U R' F R F'" },
      { name: 'Stollery', subcase: 0, alg: "U2 F2 R U R' F U' R U' R'" },
      { name: 'Stollery', subcase: 1, alg: "F2 R U2 R' F U R' F' R" },
      { name: 'Stollery', subcase: 2, alg: "F R' F' U R2 U R2 U' R" },
      { name: 'Stollery', subcase: 3, alg: "y' R2 F' R U2 R U2 R' F R " },
      { name: 'Stollery', subcase: 4, alg: "U2 R U' R' U R U2 R2 F R F'" },
      { name: 'Stollery', subcase: 5, alg: "R' F R U R U' R' F' R U' R'" },
      { name: 'Pinwheel', subcase: 0, alg: "R2 U R' U R' U2 R U2 R' U2 R" },
      { name: 'Pinwheel', subcase: 1, alg: "y' R' U' R' F R F' U2 R U' R' U R" },
      { name: 'Pinwheel', subcase: 2, alg: "U2 y' R2 F' R U2 R U R' F2 R" },
      { name: 'Pinwheel', subcase: 3, alg: "y' R2 F' R U2 R U R' F2 R" },
      { name: 'Pinwheel', subcase: 4, alg: "U' y' R2 F' R U2 R U R' F2 R" },
      { name: 'Pinwheel', subcase: 5, alg: "U y' R2 F' R U2 R U R' F2 R" },
      { name: 'Two-Face', subcase: 0, alg: "R2 U R' U R U2 R' U2 R'" },
      { name: 'Two-Face', subcase: 1, alg: "U y R' F R U' F R U R' F'" },
      { name: 'Two-Face', subcase: 2, alg: "U2 R2 U' R' F R' F' R U2 R'" },
      { name: 'Two-Face', subcase: 3, alg: "R2 U' R' F R' F' R U2 R'" },
      { name: 'Two-Face', subcase: 4, alg: "U R' F R F' R U2 R' U' R U R'" },
      { name: 'Two-Face', subcase: 5, alg: "U' R' F R F' R U2 R' U' R U R'" },
      { name: 'Turtle', subcase: 0, alg: "U' y R' F R U' R' F R" },
      { name: 'Turtle', subcase: 1, alg: "U y' R' U R U' R2 F R F' R U' R' U2 R" },
      { name: 'Turtle', subcase: 2, alg: "U' R U2 R' U2 F R' F' R" },
      { name: 'Turtle', subcase: 3, alg: "U F R F' R U R2 U' R U R'" },
      { name: 'Turtle', subcase: 4, alg: "U y' R' F R' F' R2 U R' U R" },
      { name: 'Turtle', subcase: 5, alg: "U y' F R F' U R' U2 R" },
      { name: 'Pinwheel-Poser', subcase: 0, alg: "U' F' U2 F2 R F' R U R2" },
      { name: 'Pinwheel-Poser', subcase: 1, alg: "U F U R U' R2 F' R F R' F' R" },
      { name: 'Pinwheel-Poser', subcase: 2, alg: "U' y R' F R2 U' R' F" },
      { name: 'Pinwheel-Poser', subcase: 3, alg: "U R U R' F R' F' R U2 R U' R'" },
      { name: 'Pinwheel-Poser', subcase: 4, alg: "F' R' F2 R U' F" },
      { name: 'Pinwheel-Poser', subcase: 5, alg: "U F R' F' R2 U R'" },
      { name: 'Gun', subcase: 0, alg: "U R U2 R' U2 R U R'" },
      { name: 'Gun', subcase: 1, alg: "U y' R' U2 F R F' R U R2 U' R" },
      { name: 'Gun', subcase: 2, alg: "U R U R' U' F R' F' R" },
      { name: 'Gun', subcase: 3, alg: "U' y' R' U' R U' R' F R' F' R2" },
      { name: 'Gun', subcase: 4, alg: "R2 U R' F R F' R' U' R" },
      { name: 'Gun', subcase: 5, alg: "U' y' R' F R' F' R U2 R" }
    ]
  }
};

export const BASE_PRESETS = [
  { name: '空', face: '', category: '基础' },
  { name: 'R', face: 'R', category: '基础' },
  { name: 'R U', face: 'R U', category: '基础' },
  { name: "R U R'", face: "R U R'", category: '基础' },
  { name: "R U2 R'", face: "R U2 R'", category: '基础' },
  { name: "F R U R'", face: "F R U R'", category: '基础' },
  { name: "R' D R", face: "R' D R", category: '顶层不动块bar' },
  { name: "y' F U' R'", face: "y' F U' R'", category: '顶层不动块bar' },
  { name: "F R U' R U R2", face: "F R U' R U R2", category: '顶层不动块bar' },
  { name: "B' R' U R' U' R2", face: "B' R' U R' U' R2", category: '顶层不动块bar' },
  { name: "R2 U' R' U R' F'", face: "R2 U' R' U R' F'", category: '顶层不动块bar' },
  { name: "R D R'", face: "R D R'", category: '顶层不动块not bar' },
  { name: "R F R'", face: "R F R'", category: '顶层不动块not bar' },
  { name: "F' R' F", face: "F' R' F", category: '顶层不动块not bar' },
  { name: "R U R' F' R'", face: "R U R' F' R'", category: '顶层不动块not bar' },
  { name: "R U2' R'", face: "R U2' R'", category: '简单不动块' },
  { name: "R' U2 R", face: "R' U2 R", category: '简单不动块' },
  { name: "R U R' U' F", face: "R U R' U' F", category: '简单不动块' },
  { name: "R U R' F'", face: "R U R' F'", category: 'TCLLbar+平移' },
  { name: "F R U' R'", face: "F R U' R'", category: 'TCLLbar+平移' },
  { name: "F' R' F R", face: "F' R' F R", category: 'TCLLbar+平移' },
  { name: "R' F' R F", face: "R' F' R F", category: 'TCLLbar+平移' },
  { name: "R2 U' R2'", face: "R2 U' R2'", category: 'TCLLbar+平移' },
  { name: "U' R U' R' U", face: "U' R U' R' U", category: '棋盘顶层bar' },
  { name: "R U' R' U R'", face: "R U' R' U R'", category: '棋盘顶层bar' },
  { name: "U L U' L", face: "U L U' L", category: '棋盘顶层bar' },
  { name: "U' R' U R'", face: "U' R' U R'", category: '棋盘顶层bar' },
  { name: "R2 U", face: "R2 U", category: '棋盘顶层bar' },
  { name: "R2 U R' F' R'", face: "R2 U R' F' R'", category: '棋盘顶层bar' },
  { name: "L2' U' L F L", face: "L2' U' L F L", category: '棋盘顶层bar' },
  { name: "R2' F' R F", face: "R2' F' R F", category: '底层/顶层bar' },
  { name: "L2 F L' F'", face: "L2 F L' F'", category: '底层/顶层bar' },
  { name: "R2' U R U' R", face: "R2' U R U' R", category: '底层/顶层bar' },
  { name: "R2 U' R' U R'", face: "R2 U' R' U R'", category: '底层/顶层bar' },
  { name: "R U' R U R2'", face: "R U' R U R2'", category: '底层/顶层bar' },
];